### PR TITLE
Jimmy email is added

### PR DESCRIPTION
**Pull request by Jimmy447Wang**
check now

### CODE REVIEW

**Review by WenjiZ — DISMISSED** [review]

**Review by Jack-Vu — DISMISSED** [review]

**Review by ningyang534 — DISMISSED** [review]
GREAT

**Review by ntnguyen328 — DISMISSED** [review]
Looks good!

**Review by joycechen612 — DISMISSED** [review]
great

**Comment by AnnaZhao0209** [comment]
fixed

**Review by AnnaZhao0209 — APPROVED** [review]

**Pull request closed without merging**
