### PR TITLE
I added an email under my name, Erlyn Gammad

### PR DESCRIPTION
**Pull request by gammadejs**

### CODE REVIEW

**Review by Jack-Vu — APPROVED** [review]
LGTM!

**Review by Jack-Vu — APPROVED** [review]

**Comment by Muss768** [comment]
LGTM!

**Comment by ntnguyen328** [comment]
Nice job!

**Review by ntnguyen328 — DISMISSED** [review]
Looks good!

**Review by Jack-Vu — DISMISSED** [review]

**Review by WenjiZ — DISMISSED** [review]
LGTM

**Review by KrizelC — DISMISSED** [review]

**Review by Pillow407 — DISMISSED** [review]
Please review mine also

**Review by WenjiZ — DISMISSED** [review]

**Review by Pillow407 — APPROVED** [review]
LGTM

**Pull request closed without merging**
