### PR TITLE
email is added

### PR DESCRIPTION
**Pull request by Pillow407**
Email is added

### CODE REVIEW

**Review by joycechen612 — DISMISSED** [review]
Great

**Review by WenjiZ — DISMISSED** [review]

**Review by ntnguyen328 — DISMISSED** [review]
Looks good!

**Review by ClaireDu777 — APPROVED** [review]
lgam

**Review by ClaireDu777 — APPROVED** [review]
looks better

**Review by Jack-Vu — APPROVED** [review]

**Review by WenjiZ — APPROVED** [review]

**Review by gammadejs — APPROVED** [review]
looks good

**Pull request merged**
