### PR TITLE
added email

### PR DESCRIPTION
**Pull request by ShaolingStouder**

### CODE REVIEW

**Review by ntnguyen328 — APPROVED** [review]
Looks good!

**Review by ntnguyen328 — DISMISSED** [review]
Looks good!

**Review by WenjiZ — DISMISSED** [review]

**Review by NiluparErkin — DISMISSED** [review]

**Review by joycechen612 — APPROVED** [review]
great

**Review by joycechen612 — DISMISSED** [review]
Great

**Review by WenjiZ — APPROVED** [review]

**Review by joycechen612 — APPROVED** [review]
GREAT

**Review by Wei1150 — APPROVED** [review]
LGTM

**Review by Sedefakyol12 — APPROVED** [review]
great!

**Review by ShaolingStouder — COMMENTED** [review]
Thanks!

**Pull request closed without merging**
